# Generated by Django 3.2.6 on 2022-05-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220520_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Fecha_publicaion')),
                ('author_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
    ]
