# Generated by Django 3.2.6 on 2022-05-21 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220520_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Libros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='Autor'),
        ),
    ]
