# Generated by Django 3.2.6 on 2022-05-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220520_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(to='book.Author', verbose_name='Autor'),
        ),
    ]
