# Generated by Django 3.2.6 on 2022-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220520_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_created=True, auto_now=True, verbose_name='Fecha_publicacion'),
        ),
    ]
