# Generated by Django 3.2.6 on 2022-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
