# Generated by Django 4.0.5 on 2022-06-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_author_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha_publicacion'),
        ),
    ]
